name: CI

on: [push]

jobs:
  build-enabler:
    name: Build the application for plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install modules
        run: yarn install

      - name: Compile typescript
        run: yarn run build

      - name: Audit
        run: yarn audit