name: E2E tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Run tests against
        required: true
        options:
          - dev
          - prod
          - connect_dev
          - connect_prod
jobs:
  e2e-tests:
    name: 'Running E2E tests'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run postman collection
        uses: ./.github/actions/postman
        with:
          ct_client_id: ${{ secrets.CT_E2E_CLIENT_ID }}
          ct_secret: ${{ secrets.CT_E2E_SECRET }}
          klaviyo_auth_key: ${{ secrets.KLAVIYO_AUTH_KEY }}
          postman_collection_json: "klaviyo-e2e-tests.postman_collection.json"
          ct_api_url: ${{ vars.CT_API_URL }}
          ct_auth_url: ${{ vars.CT_AUTH_URL }}
          ct_project_id: ${{ vars.CT_PROJECT_ID }}

