name: Build and and test plugin
on:
  pull_request:
    paths-ignore:
      - 'plugin/infrastructure/**'
  push:
    branches:
      - main
    paths:
      - '!plugin/infrastructure/**'
jobs:
  plugin:
    name: 'Build and test'
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 18.x ]
#    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: ./plugin/yarn.lock
      - name: Dependencies install
        working-directory: ./plugin
        run: yarn install --frozen-lockfile
      - name: Linting
        working-directory: ./plugin
        run: yarn lint
      - name: Test
        working-directory: ./plugin
        run: yarn test
