name: "Infrastructure pipeline"

on:
  pull_request:
    paths:
      - 'plugin/infrastructure/**'
      - '.github/workflows/terraform.yml'
      - '.github/actions/terraform/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run terraform
        uses: ./.github/actions/terraform
        with:
          tf_environment: dev
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          ct_tf_client_id: ${{ secrets.CT_TF_CLIENT_ID }}
          ct_tf_secret: ${{ secrets.CT_TF_SECRET }}
          klaviyo_auth_key: ${{ secrets.KLAVIYO_AUTH_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

